"use node";

import { internalAction } from "../_generated/server";
import { v } from "convex/values";
import { getSupabaseClient } from "../utils/supabase";

/**
 * Send an email with PDF attachment using Gmail API
 */
export const sendReportAction = internalAction({
    args: {
        userId: v.string(),
        pdfBase64: v.string(), // Base64 encoded PDF
        userEmail: v.string(),
    },
    handler: async (_ctx, { userId, pdfBase64, userEmail }) => {
        const SUPABASE_URL = process.env.SUPABASE_URL;
        const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

        if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
            throw new Error("Supabase not configured");
        }

        const supabase = getSupabaseClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

        // Get tokens (reuse existing logic if possible, or duplicate for speed)
        const { data: provider, error } = await supabase
            .from("auth_providers")
            .select("access_token")
            .eq("user_id", userId)
            .eq("provider", "google")
            .single();

        if (error || !provider) {
            throw new Error("Google account not linked. Please sync email first.");
        }

        const accessToken = provider.access_token;

        // Construct MIME message
        const boundary = "foo_bar_baz";
        const messageParts = [
            `From: me`,
            `To: ${userEmail}`,
            `Subject: Your InsureOS Risk Report`,
            `MIME-Version: 1.0`,
            `Content-Type: multipart/mixed; boundary="${boundary}"`,
            ``,
            `--${boundary}`,
            `Content-Type: text/plain; charset="UTF-8"`,
            `Content-Transfer-Encoding: 7bit`,
            ``,
            `Hello,`,
            ``,
            `Please find attached your personalized insurance risk analysis and policy audit report generated by InsureOS.`,
            ``,
            `Best regards,`,
            `Agent Insure`,
            ``,
            `--${boundary}`,
            `Content-Type: application/pdf; name="InsureOS_Report.pdf"`,
            `Content-Transfer-Encoding: base64`,
            `Content-Disposition: attachment; filename="InsureOS_Report.pdf"`,
            ``,
            pdfBase64,
            ``,
            `--${boundary}--`,
        ];

        const message = messageParts.join("\n");
        const encodedMessage = Buffer.from(message)
            .toString("base64")
            .replace(/\+/g, "-")
            .replace(/\//g, "_")
            .replace(/=+$/, "");

        const res = await fetch(
            "https://www.googleapis.com/gmail/v1/users/me/messages/send",
            {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${accessToken}`,
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    raw: encodedMessage,
                }),
            }
        );

        if (!res.ok) {
            const err = await res.text();
            throw new Error(`Gmail Send Failed: ${err}`);
        }

        return { status: "success" };
    },
});
